name: build

on:
  push:
  
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker run -v "$PWD":"$PWD" -w "$PWD" denoland/deno:latest run --allow-net --allow-write generate-PKGBUILD.js > PKGBUILD
      - run: cat PKGBUILD
      - run: docker run -v "$PWD":"$PWD" -w "$PWD" --user "$UID" archlinux:base-devel makepkg -g PKGBUILD >> PKGBUILD
      - run: cat PKGBUILD
      - run: docker run -v "$PWD":"$PWD" -w "$PWD" --user "$UID" archlinux:base-devel makepkg PKGBUILD
      - run: ls
      - run: docker run -v "$PWD":"$PWD" -w "$PWD" --user "$UID" archlinux:base-devel repo-add storj.db.tar.gz *.pkg*
      - run: ls
      - run: mkdir -p dist/x86_64; mv storj* dist/x86_64/; mv version dist/;
      - uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist
